services:
  - type: web
    name: job-portal
    runtime: docker
    plan: free
    # Root directory MUST be blank or . so Docker can see both /frontend and /backend
    rootDir: .
    # Dockerfile path MUST be Dockerfile
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
